language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  # create snakemake env
  - conda install pytest
  - conda create -q -n snakemake snakemake python=$TRAVIS_PYTHON_VERSION
  # add additional stuff to setup below
  - conda create -q -n bioconda bwa==0.7.15
  - source activate bioconda
  - bwa index .test/data/ref/chr21.fa
  - conda install samtools
  - samtools faidx .test/data/ref/chr21.fa
  - source activate snakemake
  - pip install pandas pyvcf pytools biopython
script:
  # run the workflow
  # put a test case into the subfolder .test (e.g., use https://github.com/snakemake-workflows/ngs-test-data as a submodule)
  - source activate snakemake
  - python -m scripts.lib.common.utils
  - python -m scripts.tests.common.data.parser.test_jspmania
  - python -m scripts.tests.common.data.parser.test_pindel
  - snakemake --use-conda --directory .test/swift -s Snakefile
  - snakemake --use-conda --directory .test/haloplex -s Snakefile
  - snakemake --use-conda --directory .test/split -s Snakefile --latency-wait 10 --verbose --restart-times 1
  
