---

samples: samples.tsv

units: units.tsv

illuminaclip_file: ../illumina.fa

reference_genome: ../data/ref/genome.chr21.fa

accel_panels:
  panel1:
    5p_primer_file: 5p_primers.fa
    3p_primer_file: 3p_primers.fa
  panel2:
    5p_primer_file: 5p_primers.fa
    3p_primer_file: 3p_primers.fa

cutadapt:
  adapters_1:
    first_pair_adapter: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
    second_pair_adapter: AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT
