---

nc_to_chr_file: ../reference.hg19.info
chr_to_nc_file: ../reference.chr_to_nc.hg19.info

pindel_exclude_regions: ../exclude.chr.txt

path_gatk: /snakemake-workflows/resources/GenomeAnalysisTKLite_molecules.jar
path_jsnpmania: /snakemake-workflows/resources/jSNPmania-0.0.7-SNAPSHOT-amplicons_v4/JSNPmania.sh
path_jsnpmania_header: ../Convert2SNPManiaHeader.sam

num_fastq_split: 3

annovar:
  build_version: hg19
  bin: /snakemake-workflows/resources/2015Mar22/bin/table_annovar.pl
  database: /snakemake-workflows/resources/2015Mar22_20160706/annovar_humandb
  protocols:
    refGene:
      argument: "'-splicing_threshold 5'"
      operation: g
    1000g2015aug_eur:
      argument: ""
      operation: f
    snp138:
      argument: ""
      operation: f
    snp138NonFlagged:
      argument: ""
      operation: f
    esp6500siv2_ea:
      argument: ""
      operation: f
    cosmic70:
      argument: ""
      operation: f
    clinvar_20150629:
      argument: ""
      operation: f

samples: samples.tsv

units: units.tsv

illuminaclip_file: ../illumina.fa

reference_genome: ../data/ref/chr21.fa
reference_genome_name: hg19.chr21.fa
reference_genome_date: 200902


accel_panels:
  panel1:
    5p_primer_file: 5p_primers.fa
    3p_primer_file: 3p_primers.fa
  panel2:
    5p_primer_file: 5p_primers.fa
    3p_primer_file: 3p_primers.fa

cutadapt:
  adapters_1:
    first_pair_adapter: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
    second_pair_adapter: AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT

pindel_flags:
  swift:
    min_read_depth: 20
    min_allele_ratio: 0.001
    read_method: min
  haloplex:
    min_read_depth: 5
    min_allele_ratio: 0.01
    read_method: min
files:
  transcripts_mappers: ../transcripts.tsv
  multibp_variants_mappers: ../multibp.tsv
  swift:
    blacklist: ../blacklist.tsv
  haloplex:
    blacklist: ../blacklist.tsv

#jsnpmania_flags: "-a 5 -q 20 -e 0 -am"
jsnpmania_flags: "-a 1 -q 0 -e 0 -am"

mutations_flags:
  swift: "-minRD 30,300 -minVaf 0.001"
  haloplex: "-minRD 30,300 -minVaf 0.01"

filter_settings:
  haloplex:
    min_allele_ratio: 0.01
    min_read_depth: 20
    amplicon_min_depth: 5
    max_1000genome_ratio: 0.02

pindel_flags:
  max_range_index: 2
  balance_cutoff: 100

annovar_pindel_flags:
  plasma:
    min_read_depth: 20
    min_allele_ratio: 0.001
    read_method: min
  ffpe:
    min_read_depth: 20
    min_allele_ratio: 0.01
    read_method: min
